### ISSUE TITLE
Filtro Productos: Categoría de Productos

### ISSUE THREAD

**Issue by molavec** [molavec/M4-ABPRO#14]
Debes incorporar un filtrado de productos para el cliente, considerando una categoría de productos (select).

**Comment by molavec** [comment]
Revisar la clase `inventory.js`, metodo `filterByCategory`, en ese punto es conveniente realizar el filtro ya que se tiene acceso al listado de productos `this.priducts`.

**Comment by molavec** [comment]
Coordinar en que parte se añadirá elemento requerido en el DOM.

**Comment by Jozz16** [comment]
Tarea finalizada.
